import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//components  
import Header from "../components/Header";
import Bag from "../components/Bag";
import Sidebar from "../components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;600;700;800;900&display=swap" rel="stylesheet"/>
      </head>

      <body >
        <main className="bg-gray-200 w-full h-full flex items-center justify-center " >
          <section>
            <Header />
            <div className="p-3 ">{children}</div>
            <Bag />
          </section>
        </main>
      </body>
    </html>
  );
}

