import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//components  
import Header from "../components/Header";
import Bag from "../components/Bag";
import { Toaster} from "react-hot-toast";
import { MarmitexProvider } from "@/context/MarmitexContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full" lang="pt">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="h-full">
        <MarmitexProvider>
          <main className=" bg-gray-200 h-full flex flex-col ">
            <Header />
            <section className="relative p-1 flex-1 overflow-auto  ">
              {children}
            </section>
            <Bag />
            <Toaster />
          </main>
        </MarmitexProvider>
      </body>
    </html>
  );
}

